-- 과목 공통코드 (SUBJECT) — 개발규칙 v2.4 부록 B-14 등록 SQL 그대로.
-- 큐넷 출제기준 체계. 대분류 13 · 중분류 108 · 합계 121 (DR-C06).
-- is_system은 전부 FALSE. 과목은 로직이 분기에 쓰지 않으므로 관리자가 수정·비활성화할 수 있다.
-- 출제기준이 개정되면 부록 B를 먼저 고치고 DR-C03의 승인 절차를 거친다.

-- 1단계: 대분류
INSERT INTO tb_csp_cmn01 (group_code, code_value, code_name, code_level, parent_code, sort_order, is_active, is_system) VALUES
    ('SUBJECT', 'GEN', '토목구조 일반 사항', 1, NULL, 1, TRUE, FALSE),
    ('SUBJECT', 'RCC', '철근콘크리트', 1, NULL, 2, TRUE, FALSE),
    ('SUBJECT', 'PSC', '프리스트레스트 콘크리트', 1, NULL, 3, TRUE, FALSE),
    ('SUBJECT', 'STM', '구조역학', 1, NULL, 4, TRUE, FALSE),
    ('SUBJECT', 'STL', '강구조', 1, NULL, 5, TRUE, FALSE),
    ('SUBJECT', 'BRG', '교량공학', 1, NULL, 6, TRUE, FALSE),
    ('SUBJECT', 'PLN', '설계기획 관리', 1, NULL, 7, TRUE, FALSE),
    ('SUBJECT', 'MNT', '유지관리', 1, NULL, 8, TRUE, FALSE),
    ('SUBJECT', 'ROD', '도로설계(도로구조물)', 1, NULL, 9, TRUE, FALSE),
    ('SUBJECT', 'APT', '공항설계(구조물)', 1, NULL, 10, TRUE, FALSE),
    ('SUBJECT', 'BDS', '교량설계', 1, NULL, 11, TRUE, FALSE),
    ('SUBJECT', 'CMG', '토목건설사업관리', 1, NULL, 12, TRUE, FALSE),
    ('SUBJECT', 'PRO', '기술사로서 품위 및 자질', 1, NULL, 13, FALSE, FALSE);
-- 2단계: 중분류
INSERT INTO tb_csp_cmn01 (group_code, code_value, code_name, code_level, parent_code, sort_order, is_active, is_system) VALUES
    ('SUBJECT', 'GEN001', '프로젝트 파악에 관한 사항', 2, 'GEN', 1, TRUE, FALSE),
    ('SUBJECT', 'GEN002', '자료조사에 관한 사항', 2, 'GEN', 2, TRUE, FALSE),
    ('SUBJECT', 'GEN003', '업무관리에 관한 사항', 2, 'GEN', 3, TRUE, FALSE),
    ('SUBJECT', 'GEN004', '하중검토에 관한 사항', 2, 'GEN', 4, TRUE, FALSE),
    ('SUBJECT', 'GEN005', '구조해석 및 검증에 관한 사항', 2, 'GEN', 5, TRUE, FALSE),
    ('SUBJECT', 'GEN006', '경제성 검토에 관한 사항', 2, 'GEN', 6, TRUE, FALSE),
    ('SUBJECT', 'GEN007', '종합검토에 관한 사항', 2, 'GEN', 7, TRUE, FALSE),
    ('SUBJECT', 'GEN008', '도서작성에 관한 사항', 2, 'GEN', 8, TRUE, FALSE),
    ('SUBJECT', 'GEN009', '구조계획에 관한 사항', 2, 'GEN', 9, TRUE, FALSE),
    ('SUBJECT', 'GEN010', '구조시스템계획에 관한 사항', 2, 'GEN', 10, TRUE, FALSE),
    ('SUBJECT', 'GEN011', '철근콘크리트 부재설계에 관한 사항', 2, 'GEN', 11, TRUE, FALSE),
    ('SUBJECT', 'GEN012', '강구조부재설계에 관한 사항', 2, 'GEN', 12, TRUE, FALSE),
    ('SUBJECT', 'GEN013', '강구조 설계 및 시공관리에 관한 사항', 2, 'GEN', 13, TRUE, FALSE),
    ('SUBJECT', 'GEN014', '콘크리트구조설계 및 시공관리에 관한 사항', 2, 'GEN', 14, TRUE, FALSE),
    ('SUBJECT', 'GEN015', '가설구조물시공 및 설계관리에 관한 사항', 2, 'GEN', 15, TRUE, FALSE),
    ('SUBJECT', 'GEN016', '지진 및 구조동역학에 관한 사항', 2, 'GEN', 16, TRUE, FALSE),
    ('SUBJECT', 'GEN017', '유체, 지반구조상호 해석에 관한 사항', 2, 'GEN', 17, TRUE, FALSE),
    ('SUBJECT', 'GEN018', '설계기준 및 해석에 관한 사항', 2, 'GEN', 18, TRUE, FALSE),
    ('SUBJECT', 'GEN019', '건설관련법규 및 정책의 이해', 2, 'GEN', 19, TRUE, FALSE),
    ('SUBJECT', 'RCC001', '철근콘크리트 재료', 2, 'RCC', 1, TRUE, FALSE),
    ('SUBJECT', 'RCC002', '역학적 성질', 2, 'RCC', 2, TRUE, FALSE),
    ('SUBJECT', 'RCC003', '설계방법과 안전성', 2, 'RCC', 3, TRUE, FALSE),
    ('SUBJECT', 'RCC004', '보의 휨 해석과 설계', 2, 'RCC', 4, TRUE, FALSE),
    ('SUBJECT', 'RCC005', '전단과 비틀림', 2, 'RCC', 5, TRUE, FALSE),
    ('SUBJECT', 'RCC006', '철근의 정착과 이음', 2, 'RCC', 6, TRUE, FALSE),
    ('SUBJECT', 'RCC007', '사용성과 내구성', 2, 'RCC', 7, TRUE, FALSE),
    ('SUBJECT', 'RCC008', '기둥', 2, 'RCC', 8, TRUE, FALSE),
    ('SUBJECT', 'RCC009', '옹벽 및 기초', 2, 'RCC', 9, TRUE, FALSE),
    ('SUBJECT', 'PSC001', '프리스트레싱 방법과 정착장치', 2, 'PSC', 1, TRUE, FALSE),
    ('SUBJECT', 'PSC002', '프리스트레스의 도입과 손실', 2, 'PSC', 2, TRUE, FALSE),
    ('SUBJECT', 'PSC003', '휨부재의 해석', 2, 'PSC', 3, TRUE, FALSE),
    ('SUBJECT', 'PSC004', '휨부재의 설계', 2, 'PSC', 4, TRUE, FALSE),
    ('SUBJECT', 'PSC005', '전단과 비틀림', 2, 'PSC', 5, TRUE, FALSE),
    ('SUBJECT', 'PSC006', '합성보', 2, 'PSC', 6, TRUE, FALSE),
    ('SUBJECT', 'PSC007', '연속보', 2, 'PSC', 7, TRUE, FALSE),
    ('SUBJECT', 'PSC008', '처짐', 2, 'PSC', 8, TRUE, FALSE),
    ('SUBJECT', 'STM001', '정역학 및 동역학의 기초', 2, 'STM', 1, TRUE, FALSE),
    ('SUBJECT', 'STM002', '재료의 역학적 성질', 2, 'STM', 2, TRUE, FALSE),
    ('SUBJECT', 'STM003', '단면의 기하학적 성질', 2, 'STM', 3, TRUE, FALSE),
    ('SUBJECT', 'STM004', '단면력과 응력', 2, 'STM', 4, TRUE, FALSE),
    ('SUBJECT', 'STM005', '정정보', 2, 'STM', 5, TRUE, FALSE),
    ('SUBJECT', 'STM006', '보의 응력', 2, 'STM', 6, TRUE, FALSE),
    ('SUBJECT', 'STM007', '정정라멘, 정정아치 및 케이블', 2, 'STM', 7, TRUE, FALSE),
    ('SUBJECT', 'STM008', '정정보의 처짐', 2, 'STM', 8, TRUE, FALSE),
    ('SUBJECT', 'STM009', '부정정보', 2, 'STM', 9, TRUE, FALSE),
    ('SUBJECT', 'STM010', '기둥', 2, 'STM', 10, TRUE, FALSE),
    ('SUBJECT', 'STM011', '정정트러스', 2, 'STM', 11, TRUE, FALSE),
    ('SUBJECT', 'STM012', '부정정의 트러스, 라멘 및 아치', 2, 'STM', 12, TRUE, FALSE),
    ('SUBJECT', 'STM013', '처짐각법', 2, 'STM', 13, TRUE, FALSE),
    ('SUBJECT', 'STM014', '모멘트분배법', 2, 'STM', 14, TRUE, FALSE),
    ('SUBJECT', 'STM015', '에너지법', 2, 'STM', 15, TRUE, FALSE),
    ('SUBJECT', 'STM016', '케이블구조', 2, 'STM', 16, TRUE, FALSE),
    ('SUBJECT', 'STL001', '설계개념', 2, 'STL', 1, TRUE, FALSE),
    ('SUBJECT', 'STL002', '강구조의 접합', 2, 'STL', 2, TRUE, FALSE),
    ('SUBJECT', 'STL003', '인장재', 2, 'STL', 3, TRUE, FALSE),
    ('SUBJECT', 'STL004', '압축재', 2, 'STL', 4, TRUE, FALSE),
    ('SUBJECT', 'STL005', '휨재', 2, 'STL', 5, TRUE, FALSE),
    ('SUBJECT', 'STL006', '조합력을 받는 부재', 2, 'STL', 6, TRUE, FALSE),
    ('SUBJECT', 'STL007', '합성재', 2, 'STL', 7, TRUE, FALSE),
    ('SUBJECT', 'STL008', '접합부 설계', 2, 'STL', 8, TRUE, FALSE),
    ('SUBJECT', 'BRG001', '교량 설계 일반', 2, 'BRG', 1, TRUE, FALSE),
    ('SUBJECT', 'BRG002', '철근 콘크리트교', 2, 'BRG', 2, TRUE, FALSE),
    ('SUBJECT', 'BRG003', 'PSC교', 2, 'BRG', 3, TRUE, FALSE),
    ('SUBJECT', 'BRG004', '강교', 2, 'BRG', 4, TRUE, FALSE),
    ('SUBJECT', 'BRG005', '합성교', 2, 'BRG', 5, TRUE, FALSE),
    ('SUBJECT', 'BRG006', '특수교(아치교, 트러스교, 케이블교 등)', 2, 'BRG', 6, TRUE, FALSE),
    ('SUBJECT', 'BRG007', '내진 및 내풍설계', 2, 'BRG', 7, TRUE, FALSE),
    ('SUBJECT', 'BRG008', '부속(부대)장치', 2, 'BRG', 8, TRUE, FALSE),
    ('SUBJECT', 'BRG009', '계측 및 유지관리', 2, 'BRG', 9, TRUE, FALSE),
    ('SUBJECT', 'PLN001', '기본구상', 2, 'PLN', 1, TRUE, FALSE),
    ('SUBJECT', 'PLN002', '타당성 조사', 2, 'PLN', 2, TRUE, FALSE),
    ('SUBJECT', 'PLN003', '기본계획수립', 2, 'PLN', 3, TRUE, FALSE),
    ('SUBJECT', 'PLN004', '설계표준화', 2, 'PLN', 4, TRUE, FALSE),
    ('SUBJECT', 'PLN005', '사업관리계획수립', 2, 'PLN', 5, TRUE, FALSE),
    ('SUBJECT', 'PLN006', '설계단계 관리계획수립', 2, 'PLN', 6, TRUE, FALSE),
    ('SUBJECT', 'PLN007', '시공단계 관리계획수립', 2, 'PLN', 7, TRUE, FALSE),
    ('SUBJECT', 'PLN008', 'VE 수행계획수립', 2, 'PLN', 8, TRUE, FALSE),
    ('SUBJECT', 'PLN009', 'BIM 수행계획수립', 2, 'PLN', 9, TRUE, FALSE),
    ('SUBJECT', 'PLN010', '건설정보체계 구축계획', 2, 'PLN', 10, TRUE, FALSE),
    ('SUBJECT', 'PLN011', '건설기술용역 종합평가계획', 2, 'PLN', 11, TRUE, FALSE),
    ('SUBJECT', 'MNT001', '유지관리 계획 수립', 2, 'MNT', 1, TRUE, FALSE),
    ('SUBJECT', 'MNT002', '유지관리 행정업무 수행', 2, 'MNT', 2, TRUE, FALSE),
    ('SUBJECT', 'MNT003', '시설물 점검 실시', 2, 'MNT', 3, TRUE, FALSE),
    ('SUBJECT', 'MNT004', '시설물 진단 실시', 2, 'MNT', 4, TRUE, FALSE),
    ('SUBJECT', 'MNT005', '시설물 성능 상태 분석', 2, 'MNT', 5, TRUE, FALSE),
    ('SUBJECT', 'MNT006', '보수·보강 설계', 2, 'MNT', 6, TRUE, FALSE),
    ('SUBJECT', 'MNT007', '보수·보강 시공 관리', 2, 'MNT', 7, TRUE, FALSE),
    ('SUBJECT', 'MNT008', '보수·보강 성능 평가', 2, 'MNT', 8, TRUE, FALSE),
    ('SUBJECT', 'ROD001', '도로설계 구조물 계획 검토', 2, 'ROD', 1, TRUE, FALSE),
    ('SUBJECT', 'ROD002', '도로설계 경제성 분석', 2, 'ROD', 2, TRUE, FALSE),
    ('SUBJECT', 'APT001', '공항설계 설계기준 수립', 2, 'APT', 1, TRUE, FALSE),
    ('SUBJECT', 'APT002', '공항설계 공종별 세부설계', 2, 'APT', 2, TRUE, FALSE),
    ('SUBJECT', 'APT003', '공항설계 도면 작성', 2, 'APT', 3, TRUE, FALSE),
    ('SUBJECT', 'APT004', '공항설계 유지관리 계획 수립', 2, 'APT', 4, TRUE, FALSE),
    ('SUBJECT', 'BDS001', '교량설계 사전자료 검토', 2, 'BDS', 1, TRUE, FALSE),
    ('SUBJECT', 'BDS002', '교량설계 사업개요 분석', 2, 'BDS', 2, TRUE, FALSE),
    ('SUBJECT', 'BDS003', '교량설계 현황 조사', 2, 'BDS', 3, TRUE, FALSE),
    ('SUBJECT', 'BDS004', '교량설계 기본계획 수립', 2, 'BDS', 4, TRUE, FALSE),
    ('SUBJECT', 'BDS005', '교량설계 형식·공법 결정', 2, 'BDS', 5, TRUE, FALSE),
    ('SUBJECT', 'BDS006', '교량설계 계산서 작성', 2, 'BDS', 6, TRUE, FALSE),
    ('SUBJECT', 'BDS007', '교량설계 도면 작성', 2, 'BDS', 7, TRUE, FALSE),
    ('SUBJECT', 'BDS008', '교량설계 시방서 작성', 2, 'BDS', 8, TRUE, FALSE),
    ('SUBJECT', 'BDS009', '교량설계 사업비 산정', 2, 'BDS', 9, TRUE, FALSE),
    ('SUBJECT', 'BDS010', '교량설계 보고서 작성', 2, 'BDS', 10, TRUE, FALSE),
    ('SUBJECT', 'CMG001', '건설사업관리계획검토', 2, 'CMG', 1, TRUE, FALSE),
    ('SUBJECT', 'CMG002', '설계도서 검토', 2, 'CMG', 2, TRUE, FALSE),
    ('SUBJECT', 'PRO001', '기술사가 갖추어야 할 주된 자질, 사명감, 인성', 2, 'PRO', 1, FALSE, FALSE),
    ('SUBJECT', 'PRO002', '기술사 자기개발과제', 2, 'PRO', 2, FALSE, FALSE);
